'''This module provides definitions and mappings used in by custompk'''

def get_pk_type_str(pktype):
    '''
    Return human readable packet type

    :param pktype: Number of packet type returned by socket.recvfrom()
    '''
    switch = {
        0:'HOST (to us)',
        1:'BROADCAST (to all)',
        2:'MULTICAST (to group)',
        3:'OTHER HOST (to sb else)',
        4:'OUTGOING (from us)',
        5:'LOOPBACK (lb bc/ms)',
        6:'USER (to user sp)',
        7:'KERNEL (to kernel sp)',
        8:'FASTROUTE'
    }
    return switch.get(pktype, '???')


def get_iana_protocol_str(ip_proto_id):
    '''
    Return human readable packet type

    :param ip_proto_id: protocol ID contained in IP header
    '''
    switch = {
        0:'HOPOPT IPv6 Hop-by-Hop Option',
        1:'ICMP Internet Control Message',
        2:'IGMP Internet Group Management',
        3:'GGP Gateway-to-Gateway',
        4:'IPv4 Iencapsulation',
        5:'ST Stream',
        6:'TCP Transmission Control Protocol',
        7:'CBT',
        8:'EGP Exterior Gateway Protocol',
        9:'IGP any private interior gateway (used by Cisco for their IGRP)',
        10:'BBN RCC Monitoring',
        11:'NVP-II Network Voice Protocol',
        12:'PUP',
        13:'ARGUS (deprecated)',
        14:'EMCON',
        15:'XNET Cross Net Debugger',
        16:'CHAOS',
        17:'UDP User Datagram Protocol',
        18:'MUX Multiplexing',
        19:'DCN-MEAS DCN Measurement Subsystems',
        20:'HMP Host Monitoring',
        21:'PRM Packet Radio Measurement',
        22:'XNS-IDP XEROX NS IDP',
        23:'TRUNK-1 Trunk-1',
        24:'TRUNK-2 Trunk-2',
        25:'LEAF-1',
        26:'LEAF-2',
        27:'RDP Reliable Data Protocol',
        28:'IRTP Internet Reliable Transaction',
        29:'ISO-TP4 ISO Transport Protocol Class 4',
        30:'NETBLT Bulk Data Transfer Protocol',
        31:'MFE-NSP MFE Network Services Protocol',
        32:'MERIT-INP MERIT Internodal Protocol',
        33:'DCCP Datagram Congestion Control Protocol',
        34:'3PC Third Party Connect Protocol',
        35:'IDPR Inter-Domain Policy Routing Protocol',
        36:'XTP',
        37:'DDP Datagram Delivery Protocol',
        38:'IDPR-CMTP IDPR Control Message Transport Proto',
        39:'TP++ Transport Protocol',
        40:'IL Transport Protocol',
        41:'IPv6 IPv6 encapsulation',
        42:'SDRP Source Demand Routing Protocol',
        43:'IPv6-Route Routing Header for IPv6',
        44:'IPv6-Frag Fragment Header for IPv6',
        45:'IDRP Inter-Domain Routing Protocol',
        46:'RSVP Reservation Protocol',
        47:'GRE Generic Routing Encapsulation',
        48:'DSR Dynamic Source Routing Protocol',
        49:'BNA',
        50:'ESP Encap Security Payload',
        51:'AH Authentication Header',
        52:'I-NLSP Integrated Net Layer Security TUBA',
        53:'SWIPE (deprecated) IP with Encryption',
        54:'NARP NBMA Address Resolution Protocol',
        55:'MOBILE IP Mobility',
        56:'TLSP Transport Layer Security Protocol using Kryptonet key management',
        57:'SKIP',
        58:'ICMP for IPv6',
        59:'IPv6-NoNxt No Next Header for IPv6',
        60:'IPv6-Opts Destination Options for IPv6',
        61:'any host internal protocol',
        62:'CFTP',
        63:'any local network',
        64:'SAT-EXPAK SATNET and Backroom EXPAK',
        65:'KRYPTOLAN Kryptolan',
        66:'RVD MIT Remote Virtual Disk Protocol',
        67:'IPPC Internet Pluribus Packet Core',
        68:'any distributed file system',
        69:'SAT-MON SATNET Monitoring',
        70:'VISA Protocol',
        71:'IPCV Internet Packet Core Utility',
        72:'CPNX Computer Protocol Network Executive',
        73:'CPHB Computer Protocol Heart Beat',
        74:'WSN Wang Span Network',
        75:'PVP Packet Video Protocol',
        76:'BR-SAT-MON Backroom SATNET Monitoring',
        77:'SUN-ND SUN ND PROTOCOL-Temporary',
        78:'WB-MON WIDEBAND Monitoring',
        79:'WB-EXPAK WIDEBAND EXPAK',
        80:'ISO-IP ISO Internet Protocol',
        81:'VMTP',
        82:'SECURE-VMTP',
        83:'VINES',
        84:'TTP Transaction Transport Protocol',
        85:'NSFNET-IGP',
        86:'DGP Dissimilar Gateway Protocol',
        87:'TCF',
        88:'EIGRP',
        89:'OSPFIGP',
        90:'Sprite-RPC Sprite RPC Protocol',
        91:'LARP Locus Address Resolution Protocol',
        92:'MTP Multicast Transport Protocol',
        93:'AX.25 Frames',
        94:'IPIP IP-within-IP Encapsulation Protocol',
        95:'MICP (deprecated) Mobile Internetworking Control Pro.',
        96:'SCC-SP Semaphore Communications Sec. Pro.',
        97:'ETHERIP Ethernet-within-IP Encapsulation',
        98:'ENCAP Encapsulation Header',
        99:'any private encryption scheme',
        100:'GMTP',
        101:'IFMP Ipsilon Flow Management Protocol',
        102:'PNNI PNNI over IP',
        103:'PIM Protocol Independent Multicast',
        104:'ARIS',
        105:'SCPS',
        106:'QNX',
        107:'A/N Active Networks',
        108:'IPComp IP Payload Compression Protocol',
        109:'SNP Sitara Networks Protocol',
        110:'Compaq-Peer Compaq Peer Protocol',
        111:'IPX-in-IP IPX in IP',
        112:'VRRP Virtual Router Redundancy Protocol',
        113:'PGM PGM Reliable Transport Protocol',
        114:'any 0-hop protocol',
        115:'L2TP Layer Two Tunneling Protocol',
        116:'DDX D-II Data Exchange (DDX)',
        117:'IATP Interactive Agent Transfer Protocol',
        118:'STP Schedule Transfer Protocol',
        119:'SRP SpectraLink Radio Protocol',
        120:'UTI',
        121:'SMP Simple Message Protocol',
        122:'SM (deprecated) Simple Multicast Protocol',
        123:'PTP Performance Transparency Protocol',
        124:'ISIS over IPv4',
        125:'FIRE',
        126:'CRTP Combat Radio Transport Protocol',
        127:'CRUDP Combat Radio User Datagram',
        128:'SSCOPMCE',
        129:'IPLT',
        130:'SPS Secure Packet Shield',
        131:'PIPE Private IP Encapsulation within IP',
        132:'SCTP Stream Control Transmission Protocol',
        133:'FC Fibre Channel',
        134:'RSVP-E2E-IGNORE',
        135:'Mobility Header',
        136:'UDPLite',
        137:'MPLS-in-IP',
        138:'manet MANET Protocols',
        139:'HIP Host Identity Protocol',
        140:'Shim6 Shim6 Protocol',
        141:'WESP Wrapped Encapsulating Security Payload',
        142:'ROHC Robust Header Compression',
        143:'Ethernet Ethernet',
        253:'Use for experimentation and testing',
        254:'Use for experimentation and testing',
        255:'Reserved'
    }
    return switch.get(ip_proto_id, 'unknown')


def get_protocol_str(proto):
    '''
    Returns human readable protocol description from a slightly shortened
    ethertype list

    :param proto: Ethertype number
    '''
    switch = {
        0x0200:'XEROX PUP (see 0A00)',
        0x0201:'PUP Addr Trans (see 0A01)',
        0x0400:'Nixdorf',
        0x0600:'XEROX NS IDP',
        0x0660:'DLOG',
        0x0661:'DLOG',
        0x0800:'Internet Protocol version 4 (IPv4)',
        0x0801:'X.75 Internet',
        0x0802:'NBS Internet',
        0x0803:'ECMA Internet',
        0x0804:'Chaosnet',
        0x0805:'X.25 Level 3',
        0x0806:'Address Resolution Protocol (ARP)',
        0x0807:'XNS Compatability',
        0x0808:'Frame Relay ARP',
        0x081c:'Symbolics Private',
        0x0900:'Ungermann-Bass net debugr',
        0x0a00:'Xerox IEEE802.3 PUP',
        0x0a01:'PUP Addr Trans',
        0x0bad:'Banyan VINES',
        0x0bae:'VINES Loopback',
        0x0baf:'VINES Echo',
        0x1000:'Berkeley Trailer nego',
        0x1600:'Valid Systems',
        0x22f3:'TRILL',
        0x22f4:'L2-IS-IS',
        0x4242:'PCS Basic Block Protocol',
        0x5208:'BBN Simnet',
        0x6000:'DEC Unassigned (Exp.)',
        0x6001:'DEC MOP Dump/Load',
        0x6002:'DEC MOP Remote Console',
        0x6003:'DEC DECNET Phase IV Route',
        0x6004:'DEC LAT',
        0x6005:'DEC Diagnostic Protocol',
        0x6006:'DEC Customer Protocol',
        0x6007:'DEC LAVC, SCA',
        0x6558:'Trans Ether Bridging',
        0x6559:'Raw Frame Relay',
        0x7000:'Ungermann-Bass download',
        0x7002:'Ungermann-Bass dia/loop',
        0x7030:'Proteon',
        0x7034:'Cabletron',
        0x8003:'Cronus VLN',
        0x8004:'Cronus Direct',
        0x8005:'HP Probe',
        0x8006:'Nestar',
        0x8008:'AT&T',
        0x8010:'Excelan',
        0x8013:'SGI diagnostics',
        0x8014:'SGI network games',
        0x8015:'SGI reserved',
        0x8016:'SGI bounce server',
        0x8019:'Apollo Domain',
        0x802e:'Tymshare',
        0x802f:'Tigan, Inc.',
        0x8035:'Reverse Address Resolution Protocol (RARP)',
        0x8036:'Aeonic Systems',
        0x8038:'DEC LANBridge',
        0x803d:'DEC Ethernet Encryption',
        0x803e:'DEC Unassigned',
        0x803f:'DEC LAN Traffic Monitor',
        0x8044:'Planning Research Corp.',
        0x8046:'AT&T',
        0x8047:'AT&T',
        0x8049:'ExperData',
        0x805b:'Stanford V Kernel exp.',
        0x805c:'Stanford V Kernel prod.',
        0x805d:'Evans & Sutherland',
        0x8060:'Little Machines',
        0x8062:'Counterpoint Computers',
        0x8065:'Univ. of Mass. @ Amherst',
        0x8066:'Univ. of Mass. @ Amherst',
        0x8067:'Veeco Integrated Auto.',
        0x8068:'General Dynamics',
        0x8069:'AT&T',
        0x806a:'Autophon',
        0x806c:'ComDesign',
        0x806d:'Computgraphic Corp.',
        0x807a:'Matra',
        0x807b:'Dansk Data Elektronik',
        0x807c:'Merit Internodal',
        0x8080:'Vitalink TransLAN III',
        0x809b:'Appletalk',
        0x809f:'Spider Systems Ltd.',
        0x80a3:'Nixdorf Computers',
        0x80c4:'Banyan Systems',
        0x80c5:'Banyan Systems',
        0x80c6:'Pacer Software',
        0x80c7:'Applitek Corporation',
        0x80d5:'IBM SNA Service on Ether',
        0x80dd:'Varian Associates',
        0x80f2:'Retix',
        0x80f3:'AppleTalk AARP (Kinetics)',
        0x80f7:'Apollo Computer',
        0x80ff:'Wellfleet Communications',
        0x8100:'Customer VLAN Tag Type',
        0x8130:'Hayes Microcomputers',
        0x8131:'VG Laboratory Systems',
        0x8148:'Logicraft',
        0x8149:'Network Computing Devices',
        0x814a:'Alpha Micro',
        0x814c:'SNMP',
        0x814d:'BIIN',
        0x814e:'BIIN',
        0x814f:'Technically Elite Concept',
        0x8150:'Rational Corp',
        0x817d:'XTP',
        0x817e:'SGI/Time Warner prop.',
        0x8180:'HIPPI-FP encapsulation',
        0x8181:'STP, HIPPI-ST',
        0x8182:'Reserved for HIPPI-6400',
        0x8183:'Reserved for HIPPI-6400',
        0x818d:'Motorola Computer',
        0x81a4:'ARAI Bunkichi',
        0x86db:'SECTRA',
        0x86de:'Delta Controls',
        0x86dd:'Internet Protocol version 6 (IPv6)',
        0x86df:'ATOMIC',
        0x876b:'TCP/IP Compression',
        0x876c:'IP Autonomous Systems',
        0x876d:'Secure Data',
        0x8808:'IEEE Std 802.3 - Ethernet Passive Optical Network (EPON)',
        0x880b:'Point-to-Point Protocol (PPP)',
        0x880c:'General Switch Management Protocol (GSMP)',
        0x8847:'MPLS',
        0x8848:'MPLS with upstream-assigned label',
        0x8861:'Multicast Channel Allocation Protocol (MCAP)',
        0x8863:'PPP over Ethernet (PPPoE) Discovery Stage',
        0x8864:'PPP over Ethernet (PPPoE) Session Stage',
        0x888e:'IEEE Std 802.1X - Port-based network access control',
        0x88a8:'IEEE Std 802.1Q - Service VLAN tag identifier (S-Tag)',
        0x88b5:'IEEE Std 802 - Local Experimental Ethertype',
        0x88b6:'IEEE Std 802 - Local Experimental Ethertype',
        0x88b7:'IEEE Std 802 - OUI Extended Ethertype',
        0x88c7:'IEEE Std 802.11 - Pre-Authentication (802.11i)',
        0x88cc:'IEEE Std 802.1AB - Link Layer Discovery Protocol (LLDP)',
        0x88e5:'IEEE Std 802.1AE - Media Access Control Security',
        0x88e7:'Provider Backbone Bridging Instance tag',
        0x88f5:'IEEE Std 802.1Q - Multiple VLAN Registration Protocol (MVRP)',
        0x88f6:'IEEE Std 802.1Q - Multiple Multicast Registration Protocol (MMRP)',
        0x890d:'IEEE Std 802.11 - Fast Roaming Remote Request (802.11r)',
        0x8917:'IEEE Std 802.21 - Media Independent Handover Protocol',
        0x8929:'IEEE Std 802.1Qbe - Multiple I-SID Registration Protocol',
        0x893b:'TRILL Fine Grained Labeling (FGL)',
        0x8940:'IEEE Std 802.1Qbg - ECP Protocol (also used in 802.1BR)',
        0x8946:'TRILL RBridge Channel',
        0x8947:'GeoNetworking as defined in ETSI EN 302 636-4-1',
        0x894f:'NSH (Network Service Header)',
        0x9000:'Loopback',
        0x9001:'3Com(Bridge) XNS Sys Mgmt',
        0x9002:'3Com(Bridge) TCP-IP Sys',
        0x9003:'3Com(Bridge) loop detect',
        0x9a22:'Multi-Topology',
        0xa0ed:'LoWPAN encapsulation',
        0xff00:'BBN VITAL-LanBridge cache',
        0xffff:'Reserved'
    }
    return switch.get(proto, '???')
